version: "3.5"

services:
  #mongo:
   # image: mongo:4
    #container_name: mongo
    #ports:
     # - 27017:27017
    #networks:
     # - counterone
    # network_mode: host
    #volumes:
     # - mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - counterone
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - counterone
    # network_mode: host
    volumes: 
      - redis:/data

networks:
  counterone:
    name: counterone-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local